config/routes.rb
Rails.application.routes.draw do
  resources :gardens, only: %i[index show] do
    resources :plants, only: :create
  end

  resources :plants, only: :destroy

  root to: 'gardens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy
  validates :name, :picture_url, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  validates :name, :picture_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden

    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'gardens/show'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_plant.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.picture_url %>)">
  <%= plant.name %>
  <%= link_to plant_path(plant), method: 'DELETE', data: { confirm: 'Are you sure?' } do %>
    <i class="fas fa-trash-alt"></i>
  <% end %>

</div>

app/views/gardens/index.html.erb
<h1>Gardens</h1>


<ul>
  <% @gardens.each do |garden| %>
    <li>
      <%= link_to garden.name, garden_path(garden) %>
    </li>
  <% end %>

</ul>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.picture_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class="container">

  <div class="cards my-5">
    <% @garden.plants.each do |plant| %>
      <%= render 'plant', plant: plant %>
    <% end %>
  </div>



  <%= render 'plants/form', garden: @garden, plant: @plant  %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/_form.html.erb
<div class="row justify-content-center">
  <div class="col-3">
    <h3>Add Plant</h3>
    <%= simple_form_for [garden, plant] do |f| %>
      <%= f.input :name %>
      <%= f.input :picture_url %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>